// =================
// TYPE NOTE
// =================
export enum NOTE_TYPE {
    UPDATE_NOTE = 'UPDATE_NOTE',
    UPDATE_NOTE_ID = 'UPDATE_NOTE_ID',
    UPDATE_NOTE_TITLE = 'UPDATE_NOTE_TITLE',
    UPDATE_NOTE_BODY = 'UPDATE_NOTE_BODY',
    UPDATE_NOTE_CREATE_AT = 'UPDATE_NOTE_CREATE_AT',
    UPDATE_NOTE_UPDATE_AT = 'UPDATE_NOTE_UPDATE_AT',
    UPDATE_STATUS_FAVORITE = 'UPDATE_STATUS_FAVORITE',
    UPDATE_STATUS_ARCHIVE = 'UPDATE_STATUS_ARCHIVE',
    RESET_NOTE = 'RESET_NOTE',
}

// =================
// TYPE LISTS
// =================
export enum LISTS_TYPE {
    UPDATE_LISTS_NOTE = 'UPDATE_LISTS_NOTE',
}
