export const UPDATE_USER_NAME = 'UPDATE_USER_NAME'
export const UPDATE_RANDOM_USER = 'UPDATE_RANDOM_USER'
export const UPDATE_SUBSCRIPTION_NAME = 'UPDATE_SUBSCRIPTION_NAME'

/**
 *  NOTE
 */
export const UPDATE_NOTE_TITLE = 'UPDATE_NOTE_TITLE';
export const UPDATE_NOTE_BODY = 'UPDATE_NOTE_BODY';
export const UPDATE_STATUS_FAVORITE = 'UPDATE_STATUS_FAVORITE';
export const UPDATE_STATUS_ARCHIVE = 'UPDATE_STATUS_ARCHIVE';
